name: api-autotests-run

on:
  push:
    branches:
      - 'master'
  
jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Python 3.12.*
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.*
        
      - name: Install pipenv
        run: pip install pipenv
        working-directory: ./api_tests
        
      - name: Local modules install
        if: ${{ always() }}
        run: pipenv install
        working-directory: ./api_tests
        
      - name: Run tests
        if: ${{ always() }}
        run: pipenv run tests_parallel_cucumberjson_report
        working-directory: ./api_tests
